In [3]:
import numpy as np

In [6]:
np.__version__

'1.16.2'

In [7]:
np?

In [9]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [10]:
L3

[True, '2', 3.0, 4]

In [11]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [12]:
np.array([3.14, 4, 2, 3]) #upcast to match types

array([3.14, 4.  , 2.  , 3.  ])

In [13]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [14]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])